# Generated by Django 6.0.6 on 2026-06-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crops", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cause", models.TextField()),
                ("recommendation", models.TextField()),
                ("dosage", models.CharField(max_length=255)),
                ("application_method", models.TextField()),
                ("tips", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "problem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solution",
                        to="crops.problem",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="solutions", to="products.product"
                    ),
                ),
            ],
            options={
                "ordering": ["problem__name"],
            },
        ),
    ]
