# Generated by Django 6.0.6 on 2026-06-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="farmer",
            name="area",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="farmer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="farmer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="farmer",
            name="phone",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
